tag: serv-sec-comp
name: Production Readiness
description: Ensuring services are ready for production deployment
draft: false
notifications:
  enabled: true
exemptions:
  enabled: true
  autoApprove: false
rules:
- title: Zero vulnerabilities in Snyk
  description: No vulnerabilities discovered through Snyk
  expression: snyk.numOfIssues() == 0
  weight: 1
  filter:
    kind: GENERIC
    types: {}
- title: MTTA for vulnerabilities is less than 5 mins
  expression: oncall.analysis(lookback = duration("P1W")).meanSecondsToFirstAck < 300
  weight: 1
  filter:
    kind: GENERIC
    types: {}
- title: Zero vulnerabilities in GitHub
  description: GitHub shows zero vulnerabilities in code
  expression: git.numOfVulnerabilities() == 0
  weight: 1
  filter:
    kind: GENERIC
    types: {}
- title: SonarQube coverage over 90%
  expression: sonarqube.metric("coverage") >= 90
  weight: 1
  filter:
    kind: GENERIC
    types: {}
- title: Zero unresolved Jira Issues
  expression: jira.numOfIssues() == 0
  weight: 1
  filter:
    kind: GENERIC
    types: {}
- title: MTTR for Vulnerabilities is less than 1 hour
  expression: oncall.analysis(lookback = duration("P1W")).meanSecondsToResolve < 3600
  weight: 1
  filter:
    kind: GENERIC
    types: {}
- title: Service has a Slack channel
  description: This service has a Slack or Teams channel set
  expression: slack != null
  weight: 1
  filter:
    kind: GENERIC
    types: {}
- title: Service has Buildkite pipelines registered
  expression: buildkite != null
  weight: 1
  filter:
    kind: GENERIC
    types: {}
filter:
  kind: GENERIC
  types:
    include:
    - service